openapi: 3.0.3
info:
  title: ServerSharedCard
  version: 1.0.0
servers:
  - url: https://192.168.49.130:8081
paths:
  /api/v1/stuff:
    get:
      tags:
        - stuff
      summary: Получить всех сотрудников
      responses:
        '200':
          description: Получение всех сотрудников
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stuff'
  /api/v1/stuff/{id}:
    get:
      tags:
        - stuff
      summary: Получить сотрудника по id
      parameters:
        - name: id
          description: id сотрудника
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: получение сотрудника
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stuff'
  /api/v1/client:
    get:
      tags:
        - client
      summary: Получить всех клиентов
      responses:
        '200':
          description: Получение всех клиентов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
  /api/v1/client/{id}:
    get:
      tags:
        - client
      summary: Получить клиента по id
      parameters:
        - name: id
          description: id клиента
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: получение клиента
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
  /api/v1/office:
    get:
      tags:
        - office
      summary: Получить все офисы
      responses:
        '200':
          description: Получение всех офисов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Office'
  /api/v1/office/{id}:
    get:
      tags:
        - office
      summary: Получить офис по id
      parameters:
        - name: id
          description: id офиса
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: получение офиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Office'
  /api/v1/offer:
    get:
      tags:
        - offer
      summary: Получить все договоры
      responses:
        '200':
          description: Получение всех договоров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
    put:
      tags:
        - offer
      summary: Добавить новый договор
      requestBody:
        description: форма для создания нового договора
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOfferParameters'
      responses:
        '200':
          description: Получение нового договора
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Offer'
  /api/v1/offer/{id}:
    get:
      tags:
        - offer
      summary: Получить договор по id
      parameters:
        - name: id
          description: id договора
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: получение договора
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
  /api/v1/offer/statistic:
    get:
      tags:
        - offer
      summary: Получить статистику по договорам
      responses:
        '200':
          description: Получение статистики
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OfferStatistic'
components:
  schemas:
    SetItem:
      properties:
        firstname:
          type: string
    Set:
      additionalProperties:
        $ref: '#/components/schemas/SetItem'
    MapItem:
      properties:
        firstname:
          type: string
        lastname:
          type: number
          format: int64
    Map:
      properties:
        default:
          $ref: '#/components/schemas/MapItem'
    OfferStatistic:
      required:
        - stuff_statistics
        - client_statistics
        - client_surnames
      type: object
      properties:
        stuff_statistics:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Map"
        client_statistics:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Map"
        client_surnames:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Set"
    NewOfferParameters:
      required:
        - client_id
        - stuff_id
        - start_date
        - ending_date
      type: object
      properties:
        client_id:
          type: string
          format: uuid
        stuff_id:
          type: string
          format: uuid
        start_date:
          type: string
          format: date
        ending_date:
          type: string
          format: date
    Stuff:
      required:
        - id
        - surname
        - name
        - patronymic
        - sex
        - birth_date
        - salary_multiplier
        - position
      type: object
      properties:
        id:
          type: string
          format: uuid
        surname:
          type: string
        name:
          type: string
        patronymic:
          type: string
        sex:
          type: boolean
        birth_date:
          type: string
          format: date
        salary_multiplier:
          type: number
          format: double
        position:
          $ref: '#/components/schemas/Position'
    Position:
      required:
        - id
        - name
        - salary
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        salary:
          type: number
          format: int
    Office:
      required:
        - id
        - name
        - address
        - law_address
        - cabinets_count
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        address:
          type: string
        law_address:
          type: boolean
        cabinets_count:
          type: number
          format: int
    Client:
      required:
        - id
        - surname
        - name
        - patronymic
        - sex
        - birth_date
        - inn
        - passport_serial
        - phone
      type: object
      properties:
        id:
          type: string
          format: uuid
        surname:
          type: string
        name:
          type: string
        patronymic:
          type: string
        sex:
          type: boolean
        birth_date:
          type: string
          format: date
        inn:
          type: string
        passport_serial:
          type: string
        phone:
          type: string
    Offer:
      required:
        - id
        - serial_number
        - sign_date
        - ending_date
        - start_date
        - stuff
        - client
        - office
      type: object
      properties:
        id:
          type: string
          format: uuid
        serial_number:
          type: string
        sign_date:
          type: string
          format: date
        ending_date:
          type: string
          format: date
        start_date:
          type: string
          format: date
        stuff:
          $ref: '#/components/schemas/Stuff'
        client:
          $ref: '#/components/schemas/Client'
        office:
          $ref: '#/components/schemas/Office'